spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}?prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true

server:
  port: 8081
